### ISSUE TITLE
Configure CORS for development

### ISSUE THREAD

**Issue by Arch-vile** [jrantamaki/supertimemachine#18]
Because webpack is exposing the resources from different port compared to the running application we need to allow CORS during development time for smooth dev experience :)

We should have a config variable to indicate we are running in development mode. I propose we specify this by giving a command line argument for the app. e.g.
`-allowCORS=localhost:8080`
to allow CORS for localhost:8080.

**Comment by jrantamaki** [comment]
implemented in pull request #21
